language: python
python:

  - "3.6"
  - "3.7"

before_install:
  - sudo apt-get install python-dev

install:
  - pip install pip --upgrade
  - pip install -r requirements.txt

script: python tests/test_all.py
branches:
  only:
    - master

deploy:
  provider: pages
  skip_cleanup: true
  github_token: bde661edb37ddb2dae94c3465df7c477f407c879
  keep_history: true
  on:
    branch: master