language: python
python:

  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - sudo apt-get install unixodbc-dev
  - sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran

install:
  - pip install pip --upgrade
  - pip install pytest
  - pip install -r requirements.txt
  - python setup.py install
script: python -m pytest -v tests/test_all.py
branches:
  only:
    - master 

deploy:
  provider: releases
  token: $GITHUB_TOKEN
  skip_cleanup: true
  skip_existing: true
  on:
    branch: master
    repo: Malachov/predictit
    tags: true