[tool.pytest.ini_options]
addopts = "--doctest-modules -x --nbmake"
usefixtures = "setup_tests"
norecursedirs = [
    "dist",
    "build",
]
doctest_optionflags = "NORMALIZE_WHITESPACE NUMBER ELLIPSIS"

[tool.black]
line-length = 110
